PREFIX fn:  <http://www.w3.org/2005/xpath-functions/#>
PREFIX dbpedia: <http://dbpedia.org/resource/>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbpprop:<http://dbpedia.org/property/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
SELECT Distinct(?universityName),?motto,?mascot
{
    ?university rdfs:label ?universityName.
    ?university dbpprop:motto ?motto.
    ?university dbpprop:mascot ?mascot.
    ?university rdf:type <http://dbpedia.org/class/yago/UniversitiesAndCollegesInLosAngelesCounty,California> .
}
group by ?universityName
LIMIT 10
